#!/bin/bash

#FILENAME: slurm.job
#SBATCH -J test2_8 # job name
#SBATCH -A bharpur # partition name
#SBATCH -N 1 # number of nodes
#SBATCH -n 1 # number of cores
#SBATCH -t 10-00:00:00
#SBATCH --mem=16000 # memory
#SBATCH --nice=100
#SBATCH -o job_out_8 # assign standard output file name
#SBATCH -e job_err_8 # assign standard error file name
#SBATCH --mail-type=end,fail # email you when begin, end, fail, requeue
#SBATCH --mail-user=ymeiborg@purdue.edu # email address

module load r/4.0.0 # load R 

echo "Beginning jobbo"

Rscript test2_8.R

echo "Done with jobbo"
